services:
  account:
    build: 
      context: ./account
      dockerfile: Dockerfile
    container_name: account-service
    ports:
      - "8000:8000"
    environment:
      CLIENT_SERVICE_BASE_URI: "http://client:8001/api"
      SERVICE_CLIENT_INFO: "/clients/{id}"
    networks:
      - bankapp
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client-service
    ports:
      - "8001:8001"
    networks:
      - bankapp

networks:
  bankapp:
    driver: bridge